{"name": "# C5121 Logout from_the_Header and verify the login page will open after logout", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \n\n", "trace": "  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\C5472_Add_new_user.py\", line 15, in lgn_w_gn_crdntls\n    context.app.main_page.lgn_w_gn_crdntls()\n  File \"C:\\Everything\\IT\\Testing\\Automation_08_09_2019\\UIautomation_python\\pages\\main_page.py\", line 148, in lgn_w_gn_crdntls\n    wait.until(EC.element_to_be_clickable(POP_UP_WNDW_OK_BTN)).click()\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\support\\wait.py\", line 80, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "steps": [{"name": "Given Loginpage", "status": "passed", "start": 1602461024184, "stop": 1602461026904}, {"name": "Then Login with the given credentials", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \n\n", "trace": "  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\C5472_Add_new_user.py\", line 15, in lgn_w_gn_crdntls\n    context.app.main_page.lgn_w_gn_crdntls()\n  File \"C:\\Everything\\IT\\Testing\\Automation_08_09_2019\\UIautomation_python\\pages\\main_page.py\", line 148, in lgn_w_gn_crdntls\n    wait.until(EC.element_to_be_clickable(POP_UP_WNDW_OK_BTN)).click()\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\support\\wait.py\", line 80, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "start": 1602461026904, "stop": 1602461040771}, {"name": "Then Hover over the Logout button at the right corner of the Header and click on the button Logout", "status": "skipped", "start": 1602461042875, "stop": 1602461042875}, {"name": "And https://devcloud.connectedio.com/login is open", "status": "skipped", "start": 1602461042875, "stop": 1602461042875}], "start": 1602461018841, "stop": 1602461042875, "uuid": "f3e7016f-3f8b-47f7-81f8-2bcdea2e2c02", "historyId": "5195210d41c1c882304aa237be7bc9a5", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "# C5121 Logout from_the_Header"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}